services:

#  --------------------------------------- PLAYGROUND ---------------------------------------
  policy-tool-frontend:
      image: nginx:alpine
      volumes:
        # Mount HTML/JS/CSS code
        - ./policy-tool-frontend:/usr/share/nginx/html/dashboard:ro
        # Mount the shared volume so Nginx can serve the generated CSVs
        - policy-tool-data:/usr/share/nginx/html/dashboard/processed
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(`reformers01.ewi.tudelft.nl`) && PathPrefix(`/dashboard`)"
        - "traefik.http.routers.dashboard.entrypoints=web,websecure"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.services.dashboard.loadbalancer.server.port=80"
      restart: always

  policy-tool-backend:
      build: ./policy-tool-backend
      volumes:
        - policy-tool-data:/app/data/processed
      environment:
        - REDIS_PASSWORD=${REDIS_PASSWORD}
      labels:
        - "traefik.enable=true"
        # path to /policy-api is needed to out frontend to make calls to the backend
        - "traefik.http.routers.policy-router.rule=Host(`reformers01.ewi.tudelft.nl`) && PathPrefix(`/policy-api`)"
        - "traefik.http.routers.policy-router.entrypoints=web,websecure"
        - "traefik.http.routers.policy-router.tls=true"
        # middleware needs to strip /policy-api so the Python code sees "/"
        - "traefik.http.middlewares.policy-strip.stripprefix.prefixes=/policy-api"
        - "traefik.http.routers.policy-router.middlewares=policy-strip"
        - "traefik.http.services.policy-service.loadbalancer.server.port=8000"
      restart: always

#  ------------------------------------END OF PLAYGROUND -------------------------------------


  ## -----------------------------------------------------------------
  ## Use Redis streams for data access of micro-services in real-time.
  ## -----------------------------------------------------------------
  redis:
    image: "redis:7.2.4-alpine"
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    restart: always

  ## -----------------------------------------------
  ## This micro-service retrieves weather forecasts.
  ## -----------------------------------------------
  weather-data-service:
    build: weather-data-service
    volumes:
      - ./weather-data-service/config.yml:/etc/data_crawler/config.yml:ro
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis
    restart: always

  ## ----------------------------------------------------------
  ## Use TimescaleDB for permanent storage of time series data.
  ## ----------------------------------------------------------
  timescale:
    image: "timescale/timescaledb-ha:pg14-latest" # Use this version for GIS support
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      TIMESCALEDB_TELEMETRY: "off"
    volumes:
      - timescale-data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432  # only for debugging

  ## ------------------------------------------------------------------------
  ## This micro-service defines the database schema used by the timescale DB.
  ## ------------------------------------------------------------------------
  db-scheme:
    image: ait1/rdp-database:latest-dev
    depends_on:
      - timescale
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DATA_SOURCE_USER: ${POSTGRES_DATA_SOURCE_USER}
      POSTGRES_DATA_SOURCE_PASSWORD: ${POSTGRES_DATA_SOURCE_PASSWORD}
      POSTGRES_DATA_VIS_USER: ${POSTGRES_DATA_VIS_USER}
      POSTGRES_DATA_VIS_PASSWORD: ${POSTGRES_DATA_VIS_PASSWORD}
      POSTGRES_DATA_PUB_VIS_USER: ${POSTGRES_DATA_PUB_VIS_USER}
      POSTGRES_DATA_PUB_VIS_PASSWORD: ${POSTGRES_DATA_PUB_VIS_PASSWORD}
      RDP_POSTGRES_HOST: timescale

  ## ----------------------------------------------------------------------------------
  ## This micro-service stores selected data from the Redis stream to the TtimescaleDB.
  ## ----------------------------------------------------------------------------------
  data-sync-service:
    image: ait1/rdp-redsql:latest-dev
    environment:
      POSTGRES_USER: ${POSTGRES_DATA_SOURCE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DATA_SOURCE_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./data-sync-service/config.yml:/etc/redsql/config.yml:ro
    depends_on:
      redis:
        condition: service_started
      db-scheme:
        condition: service_completed_successfully
    restart: always
    ## Expose ports only for debugging.
    # ports:
    #  - "5432:5432"

  ## ----------------------------------------------------------
  ## Use grafana for visualization of data in the timescale DB.
  ## ----------------------------------------------------------
  grafana:
    image: grafana/grafana-oss:10.2.3
    environment:
      GF_SERVER_ROOT_URL: "https://%(domain)s:443/grafana"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      POSTGRES_DATA_VIS_USER: ${POSTGRES_DATA_VIS_USER}
      POSTGRES_DATA_VIS_PASSWORD: ${POSTGRES_DATA_VIS_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      db-scheme:
        condition: service_completed_successfully
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=HostRegexp(`reformers01.ewi.tudelft.nl`) && (Path(`/grafana`) || PathPrefix(`/grafana/`))"
      - "traefik.http.routers.grafana.service=service-grafana"
      - "traefik.http.services.service-grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.entrypoints=web,websecure"
      - "traefik.http.routers.grafana.tls=true"

  ## ------------------------------------------------------------------------------------
  ## This micro-service uses the latest forecast data for running a PV module simulation.
  ## ------------------------------------------------------------------------------------
  pv-sim-service:
    build: pv-sim-service
    volumes:
      - ./pv-sim-service/config.yml:/app/config.yml:ro
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - weather-data-service
    restart: always

  ## -----------------------------------------------
  ## This micro-service retrieves weather forecasts.
  ## -----------------------------------------------
  frequency-data-service:
    build: frequency-data-service
    volumes:
      - ./frequency-data-service/config.yml:/etc/data_crawler/config.yml:ro
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis
    restart: always

  ## ------------------------------------------------------------------------------------
  ## This micro-service uses the latest forecast data for running a illuminator simulation.
  ## ------------------------------------------------------------------------------------
  illuminator-service:
    build: illuminator-service
    volumes:
      - ./illuminator-service/config.yml:/app/config.yml:ro
      - ./illuminator-output:/app/output
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - weather-data-service
    restart: always


  ## --------------------------------------------------
  ## Use a reverse proxy to secure this RDP deployment.
  ## --------------------------------------------------
  reverse-proxy:
    image: traefik:v3.6
    user: root
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # expose dashboard port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs/config.yml:/etc/traefik/dynamic_conf.yml:ro
      - ${PATH_TO_CERT_FILE}:/etc/traefik/certs/reformers01.ewi.tudelft.nl.crt:ro
      - ${PATH_TO_KEY_FILE}:/etc/traefik/certs/reformers01.ewi.tudelft.nl.key:ro
    restart: always
    command:
      - "--log.level=INFO"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.watch=true"
      - "--providers.file.filename=/etc/traefik/dynamic_conf.yml"
      - "--providers.docker=true"
      - "--api.insecure=true"  # enable Traefik dashboard
      - "--api.dashboard=true" # explicitly enable dashboard (safe to add)

  # ## -------------------------------------------------- 
  # ## Expose the WFS API through the reverse proxy. This container is for static publishing a static WFS file.
  # ## Accessible at: http://localhost/wfs and https://localhost/wfs
  # ## --------------------------------------------------
  # wfs-api:
  #   build: ./api
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.wfs.rule=HostRegexp(`localhost`) && (Path(`/wfs`) || PathPrefix(`/wfs/`))"
  #     - "traefik.http.routers.wfs.entrypoints=web,websecure"
  #     - "traefik.http.routers.wfs.tls=true"
  #     - "traefik.http.routers.wfs.service=service-wfs"
  #     - "traefik.http.services.service-wfs.loadbalancer.server.port=8000"

  #   depends_on:
  #     - reverse-proxy

  ## --------------------------------------------------
  ## Setup GeoServer API through the reverse proxy.
  ## Accessible at: http://localhost/geoserver and https://localhost/geoserver
  ## --------------------------------------------------
  geo:
    image: kartoza/geoserver:latest
    environment:
      - STABLE_EXTENSIONS=postgis-plugin
      - GEOSERVER_ADMIN_USER=admin # TODO: replace later
      - GEOSERVER_ADMIN_PASSWORD=geoserver # TODO: replace later
    volumes:
      - ./geo:/opt/geoserver/data_dir  # optional: persistent config/data
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geoserver.rule=Host(`reformers01.ewi.tudelft.nl`) && PathPrefix(`/geoserver`)"
      - "traefik.http.routers.geoserver.entrypoints=web,websecure"
      - "traefik.http.routers.geoserver.tls=true"
      - "traefik.http.routers.geoserver.service=service-geoserver"
      - "traefik.http.services.service-geoserver.loadbalancer.server.port=8080"
  
  ## --------------------------------------------------
  ## Publishes GeoJSON files to GeoServer.
  ## --------------------------------------------------
  geojson-loader:
    image: curlimages/curl
    depends_on:
      - geo
    entrypoint: ["sh", "-c"]
    command: ["/scripts/publish-geojson.sh"]
    volumes:
      - ./scripts:/scripts

  ## --------------------------------------------------
  ## Pushes layer to  GeoServer through the same network.
  ## --------------------------------------------------
  layer-publisher:
    build: ./layer-publisher
    depends_on:
      - geo
    networks:
      - default
    volumes:
      - ./geo:/opt/geoserver/data_dir


  ## ---------------------------------------------------------------------------------
  ## For debugging: use Redis Insight browser to explore the content of redis streams.
  ## ---------------------------------------------------------------------------------
  redis-insight:
    image: redis/redisinsight
    restart: always
    environment:
      - RI_REDIS_HOST0=redis
      - RI_REDIS_PORT0=6379
      - RI_REDIS_PASSWORD0=${REDIS_PASSWORD}
      - RI_REDIS_ALIAS0=Tutorial Redis Database
    ports:
      - 5540:5540
    depends_on:
      - redis


volumes:
  redis-data:
  timescale-data:
  grafana-data:
  volumes:
  policy-tool-data:
